
A <- commandArgs( trailingOnly=T );

#CENTERS <- scan(       A[[1]] ); # vector of data points
#MAD     <- as.double(  A[[2]] ); # "slack" to use around all data points

M <- as.matrix( read.table( A[[1]] ) ); # the "omega" matrix of the spline basis

grad <- function(x,m) { c(
x[1]*m[1,0] + x[2]*m[2,0] + x[1]*m[0,1] + x[2]*m[0,2] + 2*x[0]*m[0,0],
x[0]*m[0,1] + x[2]*m[2,1] + x[0]*m[1,0] + x[2]*m[1,2] + 2*x[1]*m[1,1],
x[0]*m[0,2] + x[1]*m[1,2] + x[0]*m[2,0] + x[1]*m[2,1] + 2*x[2]*m[2,2]) }
#source('grad.R');

o <- optim(
	CENTERS, # starting values
	function(x,m) { t(x) %*% m %*% x }, # a quadratic form
	grad,    # A gradient function (generated by grad.py)
	M,       # The matrix argument (2nd) to the func and gradient
	method="L-BFGS-B",
	lower=CENTERS-MAD,
	upper=CENTERS+MAD );

